### ISSUE TITLE
It has something wrong with full-width punctuation!

### ISSUE THREAD

**Issue by carlxwz** [IOC/dokuwiki-aceeditor#3]
Hello I am a Chinese user.
So beautiful it is.
It has something wrong with full-width Chinese punctuation on the cursor !
Wish to fix it to be more perfectful!

**Comment by albertgasset** [comment]
Sorry for the inconvenience, but this bug is not specific to this plugin. I think Chinese is not supported in Ace editor (I've tested their demo in http://ajaxorg.github.com/ace/build/editor.html).
Could you open this issue in the Ace project?  It's also in github: https://github.com/ajaxorg/ace/issues

**Comment by albertgasset** [comment]
Ace developers have fixed this bug. and the last version of the plugin includes the fix.
